import type { ToolMeta } from '../types';

export const TOOLS: ToolMeta[] = [
  {
    id: 'home',
    name: 'Dashboard',
    description: 'Platform overview and tool launcher.',
    icon: 'LayoutDashboard',
    category: 'active',
    tags: [],
  },
  {
    id: 'visual-calibration',
    name: 'Visual Calibration',
    description: 'Validate projector screen brightness (fL) and uniformity against SMPTE 196M standards using 5-point lux measurements.',
    icon: 'MonitorPlay',
    category: 'active',
    tags: ['Projector', 'Lux', 'SMPTE', 'Screen'],
  },
  {
    id: 'thermal-load',
    name: 'Thermal Load',
    description: 'Calculate total rack heat dissipation in watts and BTU/hr. Validate installed cooling capacity against actual load.',
    icon: 'Thermometer',
    category: 'active',
    tags: ['Heat', 'BTU', 'Rack', 'Cooling'],
  },
  {
    id: 'airflow',
    name: 'Airflow Optimisation',
    description: 'Calculate required vs. available CFM based on heat load. Evaluate airflow direction and estimate temperature rise.',
    icon: 'Wind',
    category: 'active',
    tags: ['CFM', 'Fans', 'Temperature', 'Cooling'],
  },
  {
    id: 'speaker-calibration',
    name: 'Speaker Calibration',
    description: 'Channel SPL balance, delay alignment, crossover review, and subwoofer integration for home theatre systems.',
    icon: 'Speaker',
    category: 'active',
    tags: ['SPL', 'Audio', 'Delay', 'Crossover'],
  },
  {
    id: 'network-quality',
    name: 'Network Audit',
    description: 'Signal coverage, internet quality, wired backbone review, and smart home readiness assessment.',
    icon: 'Network',
    category: 'active',
    tags: ['RSSI', 'Latency', 'WiFi', 'Coverage'],
  },
  {
    id: 'wifi-signal',
    name: 'WiFi Signal Strength',
    description: 'Granular AP-level mapping, roaming threshold validation, and dead zone identification.',
    icon: 'Wifi',
    category: 'future',
    tags: ['RSSI', 'AP Mapping', 'Roaming'],
  },
  {
    id: 'system-responsiveness',
    name: 'System Responsiveness',
    description: 'Measure end-to-end control system latency and classify responsiveness performance.',
    icon: 'Zap',
    category: 'future',
    tags: ['Latency', 'Control', 'Performance'],
  },
  {
    id: 'reliability-score',
    name: 'Reliability Score Engine',
    description: 'Aggregate all tool outputs into a single system health score with risk classification and priority fixes.',
    icon: 'ShieldCheck',
    category: 'future',
    tags: ['Score', 'Health', 'Risk', 'Aggregate'],
  },
  {
    id: 'av-commissioning',
    name: 'AV Commissioning',
    description: 'Structured final commissioning checklist — sources, scenes, control validation, and sign-off certificate.',
    icon: 'CheckSquare',
    category: 'future',
    tags: ['Checklist', 'Handover', 'Sign-off'],
  },
];
